### PR TITLE
Rebase to Go 1.6

### PR DESCRIPTION
**Pull request by cyli**
Signed-off-by: cyli cyli@twistedmatrix.com

### CODE REVIEW

**Comment by tiborvass** [comment]
Thanks!

**Comment by calavera** [comment]
LGTM

/cc @jfrazelle

**Comment by jessfraz** [comment]
oh jeez so old so sorry LGTM

**Comment by cyli** [comment]
@jfrazelle No worries!  thank you!  :D

**Comment by jessfraz** [comment]
next time feel free to just throw something :P

On Thu, Mar 3, 2016 at 11:56 AM, Ying Li notifications@github.com wrote:

> @jfrazelle https://github.com/jfrazelle No worries! thank you! :D
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/docker/go/pull/4#issuecomment-191935417.

## 

Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3

**Comment by lucab** [comment]
Stealing this thread to ping maintainers: this is now two golang versions behind, has this package been deprecated for something else in the meanwhile? If not, any chance to get a rebase against 1.8+?

Thanks!
(a random observer who landed here via [OCI](https://github.com/opencontainers/image-spec/blob/319fb0a1b9831ec33978f905c1a17e7e4084438e/considerations.md#json))

**Comment by cyli** [comment]
@lucab Opened https://github.com/docker/go/pull/6

**Pull request merged**
